### PR TITLE
Query gas price via getFeeData for optimal pricing on OP Bedrock

### LINKED ISSUE #25: OP Bedrock Gas Fees need to be fixed
It seems like presently the gas estimate is using old optimism logic, which is now broken under Bedrock. This is namely setting the gas fee under the hood to 1.5 gwei which is a massive overestimation now, in light of Bedrock on OP

### PR DESCRIPTION
**Pull request by bghughes**
Close #25

### CODE REVIEW

File: executionClients/marketMaking/GenericMarketMakingBot.ts [hunk 1]
```diff
@@ -121,6 +121,7 @@ export class GenericMarketMakingBot {
                 // Print the formatted ladder
                 return _uniQueryLadder;
             },
+            // TODO: Extrapolate this to config
```
Comment (bghughes) [inline executionClients/marketMaking/GenericMarketMakingBot.ts:124]: #19

**Comment by bghughes** [comment]
Note the new issue created from this, #27
